steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "--build-arg", "REACT_APP_API_URL=${_REACT_APP_API_URL}", "-t", "gcr.io/${PROJECT_ID}/brain-view-ui", "."]
images:
  - "gcr.io/${PROJECT_ID}/brain-view-ui"
